In [8]:
import pandas as pd
df = pd.read_csv('newData.txt', sep = '\s+', engine = 'python', skiprows = 15)
df = df.T
#print(df)
#print("swap:")
for i in range(0,df.shape[1], 1):
    if(pd.isna(df.at[df.index[4], i])):
        df[i] = df[i].shift(periods=2, freq=None, axis=0)
        
df=df.T
for i in range(1,df.shape[0], 1):
    if(pd.isna(df.at[df.index[i], 'TrgID'])):
        df.at[df.index[i], 'TrgID'] = df.at[df.index[i-1], 'TrgID']
#print(df.at[df.index[2], 'TrgID'])
#Outdated method
l0x = [[0] * 28, [0]*28, [0]*28]
l1x = [[0] * 28, [0]*28, [0]*28]
l2x = [[0] * 28, [0]*28, [0]*28]
l3x = [[0] * 28, [0]*28, [0]*28]

i = 0
while(df.at[df.index[i], 'TrgID'] == 0):
    l0x[int((df.at[df.index[i], 'Brd'])/2)][int(df.at[df.index[i], 'Ch'])] = df.at[df.index[i], 'LG']
    i+=1
while(df.at[df.index[i], 'TrgID'] == 1):
    l1x[int((df.at[df.index[i], 'Brd'])/2)][int(df.at[df.index[i], 'Ch'])] = df.at[df.index[i], 'LG']
    i+=1
while(df.at[df.index[i], 'TrgID'] == 2):
    l2x[int((df.at[df.index[i], 'Brd'])/2)][int(df.at[df.index[i], 'Ch'])] = df.at[df.index[i], 'LG']
    i+=1
while(i< df.shape[0] and df.at[df.index[i], 'TrgID'] == 3):
    l3x[int((df.at[df.index[i], 'Brd'])/2)][int(df.at[df.index[i], 'Ch'])] = df.at[df.index[i], 'LG']
    i+=1

print("Event 0:")
print(l0x)
print("Event 1:")
print(l1x)
print("Event 2:")
print(l2x)
print("Event 3:")
print(l3x)

#New method    total[event][detector level: 0 = top][channel: 0 = rightmost triangle]
total = []
id = 0
i=0
while(id <= int(df.at[df.index[df.shape[0]-1], 'TrgID'])):
    print(df.at[df.index[df.shape[0]-1], 'TrgID'])
    
    total.append([[0] * 28, [0]*28, [0]*28])
    while(i< df.shape[0] and df.at[df.index[i], 'TrgID'] == id):
        print("Entry:")
        print(id)
        print(int((df.at[df.index[i], 'Brd'])/2))
        print(int(df.at[df.index[i], 'Ch']))
        print(df.at[df.index[i], 'LG'])
        total[id][int((df.at[df.index[i], 'Brd'])/2)][int(df.at[df.index[i], 'Ch'])] = df.at[df.index[i], 'LG']
        i+=1
    id +=1
    
print("3D array of awsomeness:")
print(total)

df

Event 0:
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 500.0, 25.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40.0, 400.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 250.0, 250.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
Event 1:
[[240.0, 260.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50.0, 540.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 200.0, 300.0, 0, 0]]
Event 2:
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 600.0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 70.0, 380.0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 350.0, 60.0, 0, 0, 0, 0, 0, 0, 35.0]]
Event 3:
[[0, 0, 0, 0, 0, 0, 0, 0, 200.0, 310.0, 0, 0, 0, 0, 380.0, 20.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 444.0, 55.0, 0, 400.0, 64.0, 40.0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 350.0, 90.0, 22.0, 1000.0, 18.0, 0]]
3.0
Entry:
0
0
14
500.0
Entry:
0
0
15
25.0
Entry:
0
1
15
40.0
Entry:
0
1
16
400.0
Entry:
0
2
16
250.0
Entry:
0
2
17
250.0
3.0
Entry:
1
0
0
240.0
Entry:
1
0
1
260.0
Entry:
1
1
12
50.0
Entry:
1
1
13
540.0
Entry:
1
2
24
200.0
Entry:
1
2
25
300.0
3.0
Entry:
2
0
25
600.0
Entry:
2
1
21
70.0
Entry:
2
1
22
380.0
Entry:
2
2
19
350.0
Entry:
2
2
20
60.0
Entry:
2
2
27
35.0
3.0
Entry:
3
0
8
200.0
Entry:
3
0
9
310.0
Entry:
3
0
14
380.0
Entry:
3
0
15
20.0
Entry:
3
1
16
444.0
Entry:
3
1
17
55.0
Entry:
3
1
19
400.0
Entry:
3
1
20
64.0
Entry:
3
1
21
40.0
Entry:
3
2
22
350.0
Entry:
3
2
23
90.0
Entry:
3
2
24
22.0
Entry:
3
2
25
1000.0
Entry:
3
2
26
18.0
3D array of awsomeness:
[[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 500.0, 25.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40.0, 400.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 250.0, 250.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[240.0, 260.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50.0, 540.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 200.0, 300.0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 600.0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 70.0, 380.0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 350.0, 60.0, 0, 0, 0, 0, 0, 0, 35.0]], [[0, 0, 0, 0, 0, 0, 0, 0, 200.0, 310.0, 0, 0, 0, 0, 380.0, 20.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 444.0, 55.0, 0, 400.0, 64.0, 40.0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 350.0, 90.0, 22.0, 1000.0, 18.0, 0]]]

    Tstamp_us  TrgID  Brd    Ch      LG     HG
0   10000.555    0.0  0.0  14.0   500.0   39.0
1         NaN    0.0  0.0  15.0    25.0   41.0
2   10001.808    0.0  2.0  15.0    40.0   44.0
3         NaN    0.0  2.0  16.0   400.0  110.0
4    9965.050    0.0  4.0  16.0   250.0   36.0
5         NaN    0.0  4.0  17.0   250.0   34.0
6   15000.189    1.0  0.0   0.0   240.0   39.0
7         NaN    1.0  0.0   1.0   260.0   41.0
8   15054.077    1.0  2.0  12.0    50.0   44.0
9         NaN    1.0  2.0  13.0   540.0  110.0
10  15280.066    1.0  4.0  24.0   200.0   36.0
11        NaN    1.0  4.0  25.0   300.0   34.0
12  20000.543    2.0  0.0  25.0   600.0   39.0
13  21001.708    2.0  2.0  21.0    70.0   44.0
14        NaN    2.0  2.0  22.0   380.0  110.0
15  19965.000    2.0  4.0  19.0   350.0   36.0
16        NaN    2.0  4.0  20.0    60.0   34.0
17        NaN    2.0  4.0  27.0    35.0   34.0
18  28000.543    3.0  0.0   8.0   200.0   39.0
19        NaN    3.0  0.0   9.0   310.0  110.0
20        NaN    3.0  0.0  14.0   380.0  110.0
21        NaN    3.0  0.0  15.0    20.0  110.0
22  28701.334    3.0  2.0  16.0   444.0   44.0
23        NaN    3.0  2.0  17.0    55.0  110.0
24        NaN    3.0  2.0  19.0   400.0  110.0
25        NaN    3.0  2.0  20.0    64.0  110.0
26        NaN    3.0  2.0  21.0    40.0  110.0
27  29265.040    3.0  4.0  22.0   350.0   36.0
28        NaN    3.0  4.0  23.0    90.0   34.0
29        NaN    3.0  4.0  24.0    22.0   34.0
30        NaN    3.0  4.0  25.0  1000.0  110.0
31        NaN    3.0  4.0  26.0    18.0  110.0